parameters:
#    live_php.example.class: MBence\LivePHPBundle\Example

services:
#    live_php.example:
#        class: %live_php.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
